version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # Nao precisa usar o root mas eh permitido
      MYSQL_USER: 'user'
      # Password do usuario user
      MYSQL_PASSWORD: 'p@ssword'
      # Password do usuario root
      MYSQL_ROOT_PASSWORD: 'p@ssword'
    ports:
      # <Porta exposta> : < Porta do mysql dentro do container>
      - '3306:3306'
    expose:
      # Expoe a porta 3306 do container
      - '3306'
      # Persistencia dos dados (mapeamento container >> sistema hospedeiro)
    volumes:
      - mydb:/var/lib/mysql
# Names our volume
volumes:
  mydb: